# Generated by Django 5.2.4 on 2025-07-22 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address_details',
            field=models.CharField(blank=True, help_text='Specific address or landmark', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='search.location'),
        ),
    ]
