# Generated by Django 5.2.4 on 2025-07-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_address_details_alter_event_location'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Select relevant tags for this event', to='search.eventtag'),
        ),
    ]
