# Generated by Django 5.2.4 on 2025-07-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtag',
            name='color_code',
            field=models.CharField(default='#6c757d', help_text='Hex color code for the tag', max_length=7),
        ),
    ]
